#!/usr/bin/env ruby

require 'rubygems'
require 'rubigen'

if %w(-v --version).include? ARGV.first
  require '<%= name %>/version'
  puts "#{File.basename($0)} #{<%= app_model_name %>::VERSION}"
  exit(0)
end

require 'rubigen/scripts/generate'
source = RubiGen::PathSource.new(:application, 
  File.join(File.dirname(__FILE__), "../app_generators"))
RubiGen::Base.reset_sources
RubiGen::Base.append_sources source
RubiGen::Scripts::Generate.new.run(ARGV, :generator => '<%= name %>')
