#!/usr/bin/env ruby
APP_ROOT = File.join(File.dirname(__FILE__), '..')

require File.join(File.dirname(__FILE__), %w[.. lib rubigen])
require 'rubigen/scripts/generate'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! :rubygems, :newgem
RubiGen::Scripts::Generate.new.run(ARGV)
